#!/usr/bin/env python3
"""Generate `synthetic-stress-hetero.jsonl`: a heterogeneous scroll capture.

Same envelope as fixtures/msp/make-stress-300.py, but every turn carries two
bash toolCalls with a 60-line visibleOutput, a long markdown agentMessage
(heading, bullets, a 30-line fenced code block, paragraphs) — the shape of a
real "What is in this workspace?" session, so the transcript is scrollable
*and* heterogeneous (the H-1 instrument needs both; the uniform stress
capture and the short heterogeneous captures cannot show re-basing).

The `synthetic-` prefix is load-bearing: nothing here was ever on a wire, and
it must never be read as evidence of what Muse does.

Sends and costs: nothing. This script never spawns `muse` or opens a
connection — it only writes a `.jsonl` capture file by hand, fed later to
`--replay` or `--bench`, so it is free under the spend rule in `CLAUDE.md`.
"""
import argparse
import json
import sys

SID = "synthetic-stress-hetero"

CODE = "\n".join(
    f"    let value_{i} = compute_thing({i}, &state).unwrap_or_default(); // line {i}" for i in range(30)
)

PROSE = (
    "The workspace holds a Cargo workspace with three crates. The harness crate owns the "
    "window, the sidebar and the transcript; muse-client owns the wire; muse-adapter folds "
    "the stream into turns. Nothing here is optimistic: rows move on the server's word."
)


def frame(method, params):
    return "<-- " + json.dumps({"jsonrpc": "2.0", "method": method, "params": params}, separators=(",", ":"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--turns", type=int, default=80)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    seq = [0]

    def cursor():
        seq[0] += 1
        return f"v:hetero:{seq[0]}"

    def rng(first):
        return {"stream": {"kind": "session", "id": SID}, "first": {"id": f"rec-{first}", "sequence": first}, "last": {"id": f"rec-{first}", "sequence": first}}

    lines = [frame("session/started", {"viewCursor": cursor(), "session": {
        "sessionId": SID, "workspaceRoot": "/tmp/synthetic", "modelId": "muse-spark-1.3", "status": "idle",
        "createdAt": "2026-09-10T00:00:00Z", "updatedAt": "2026-09-10T00:00:00Z", "turnCount": 0,
        "approvalMode": {"mode": "onRequest", "source": "session"}, "path": "/tmp/synthetic/session.jsonl", "activeTurnId": None}})]
    rec = 1000
    for n in range(1, args.turns + 1):
        turn = f"t-hetero-{n}"
        lines.append(frame("turn/started", {"viewCursor": cursor(), "sessionId": SID, "turnId": turn}))
        lines.append(frame("item/completed", {"viewCursor": cursor(), "sessionId": SID, "item": {
            "itemId": f"i-h-user-{n}", "kind": "userMessage", "turnId": turn, "revision": 1, "status": "completed",
            "text": f"What is in this workspace? (round {n})"}}))
        for k, command in enumerate(["ls -R crates | head -60", "git log --oneline -60"]):
            rec += 1
            out = "\n".join(f"crates/harness/src/file_{n}_{k}_{i}.rs  {i * 37 % 1000} bytes" for i in range(60)) + "\n"
            item = {"itemId": f"i-h-bash-{n}-{k}", "kind": "toolCall", "turnId": turn, "revision": 2, "status": "completed",
                    "tool": "bash", "callId": f"call_h_{n}_{k}", "args": json.dumps({"command": command, "description": "List"}),
                    "visibleOutput": out, "exitCode": 0, "durationMs": 900 + k}
            lines.append(frame("item/completed", {"viewCursor": cursor(), "sessionId": SID, "item": item, "sourceRange": rng(rec)}))
        body = (f"## Workspace overview {n}\n\n{PROSE}\n\n- `crates/harness` — the app\n- `crates/muse-client` — the wire\n"
                f"- `crates/muse-adapter` — the fold\n\n```rust\nfn main_{n}() {{\n{CODE}\n}}\n```\n\n{PROSE}\n\n{PROSE}")
        lines.append(frame("item/completed", {"viewCursor": cursor(), "sessionId": SID, "item": {
            "itemId": f"i-h-agent-{n}", "kind": "agentMessage", "turnId": turn, "revision": 1, "status": "completed", "text": body}}))
        rec += 1
        lines.append(frame("turn/completed", {"viewCursor": cursor(), "sessionId": SID, "turnId": turn, "terminal": "completed",
                                              "durationMs": 1200, "sourceRange": rng(rec)}))
    with open(args.out, "w") as fh:
        fh.write("# synthetic-stress-hetero.jsonl — GENERATED by fixtures/msp/make-stress-hetero.py, not a wire capture.\n")
        fh.write("#\n")
        fh.write("# 80 heterogeneous turns (two 60-line shell cards, a 30-line rust block and\n")
        fh.write("# three paragraphs per turn) for the scroll-cadence instruments: scrollable\n")
        fh.write("# *and* heterogeneous, so height-hint re-basing (H-1) can show. Regenerate with:\n")
        fh.write("#\n")
        fh.write("#   python3 fixtures/msp/make-stress-hetero.py --turns 80 --out fixtures/msp/synthetic-stress-hetero.jsonl\n")
        fh.write("#\n")
        fh.write("# The `synthetic-` prefix is load-bearing: nothing here was ever on a wire, and\n")
        fh.write("# it must never be read as evidence of what Muse does.\n")
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {args.turns} turns, {len(lines)} frames")


if __name__ == "__main__":
    sys.exit(main())
