#!/usr/bin/env python3
"""Generate `synthetic-stress-300.jsonl`: ~300 turns for scroll benchmarks.

The turn envelope mirrors the hand-written `synthetic-todo-goal.jsonl` (same
`session/started`, `turn/started`, `userMessage` / `agentMessage`
`item/completed`, `turn/completed` shapes), re-emitted with fresh ids so the
fold keeps every turn. Every 10th turn carries three consecutive `bash`
toolCall items in the `synthetic-readoutput.jsonl` shape, which is the run
Task B folds into one `Block::ToolGroup`.

`--turns N` varies the size (used for the bounded-cost comparison).

The `synthetic-` prefix is load-bearing: nothing here was ever on a wire, and
it must never be read as evidence of what Muse does.

Sends and costs: nothing. This script never spawns `muse` or opens a
connection — it only writes a `.jsonl` capture file by hand, fed later to
`--replay`, so it is free under the spend rule in `CLAUDE.md`.
"""

import argparse
import json
import sys

SID = "synthetic-stress-300"

PARAGRAPHS = [
    "Address validation now branches per country, with the CA and GB rules covered by focused tests.",
    "The checkout form keeps its layout: the toolbar stays above the turn and never shifts it.",
    "Shell output folds after six lines, with the overflow count on the fold row.",
    "Backfill pages oldest-first through `view/page`, which is the contiguous, ordered, bounded path.",
]

COMMANDS = [
    ("cargo test --workspace", "Full workspace test run"),
    ("cargo clippy --workspace --all-targets", "Lint the workspace"),
    ("cargo build --workspace", "Full workspace build"),
]


def frame(method, params):
    return "<-- " + json.dumps({"jsonrpc": "2.0", "method": method, "params": params}, separators=(",", ":"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--turns", type=int, default=300)
    ap.add_argument("--out", default="fixtures/msp/synthetic-stress-300.jsonl")
    args = ap.parse_args()

    seq = [0]

    def cursor():
        seq[0] += 1
        return f"v:stress:{seq[0]}"

    def rng(stream, first):
        return {
            "stream": {"kind": "session", "id": SID},
            "first": {"id": f"rec-{first}", "sequence": first},
            "last": {"id": f"rec-{first}", "sequence": first},
        }

    lines = []
    lines.append(frame("session/started", {
        "viewCursor": cursor(),
        "session": {
            "sessionId": SID, "workspaceRoot": "/tmp/synthetic", "modelId": "muse-spark-1.3",
            "status": "idle", "createdAt": "2026-09-10T00:00:00Z", "updatedAt": "2026-09-10T00:00:00Z",
            "turnCount": 0, "approvalMode": {"mode": "onRequest", "source": "session"},
            "path": "/tmp/synthetic/session.jsonl", "activeTurnId": None,
        },
    }))
    rec = 1000
    for n in range(1, args.turns + 1):
        turn = f"t-stress-{n}"
        lines.append(frame("turn/started", {"viewCursor": cursor(), "sessionId": SID, "turnId": turn}))
        lines.append(frame("item/completed", {"viewCursor": cursor(), "sessionId": SID, "item": {
            "itemId": f"i-stress-user-{n}", "kind": "userMessage", "turnId": turn,
            "revision": 1, "status": "completed",
            "text": f"Checkpoint {n}: tighten validation round {n}.",
        }}))
        if n % 10 == 0:
            for k, (command, description) in enumerate(COMMANDS):
                rec += 1
                call = f"call_stress_{n}_{k}"
                item = {
                    "itemId": f"i-stress-bash-{n}-{k}", "kind": "toolCall", "turnId": turn,
                    "revision": 2, "status": "completed", "tool": "bash", "callId": call,
                    "args": json.dumps({"command": command, "description": description}),
                    "visibleOutput": f"[run {n}] {command}\n[run {n}] ok in 1.{k}s\n",
                    "exitCode": 0, "durationMs": 1100 + k,
                }
                lines.append(frame("item/completed", {
                    "viewCursor": cursor(), "sessionId": SID, "item": item,
                    "sourceRange": rng(SID, rec),
                }))
        body = PARAGRAPHS[n % len(PARAGRAPHS)] + f" (checkpoint {n} of {args.turns})"
        lines.append(frame("item/completed", {"viewCursor": cursor(), "sessionId": SID, "item": {
            "itemId": f"i-stress-agent-{n}", "kind": "agentMessage", "turnId": turn,
            "revision": 1, "status": "completed", "text": body,
        }}))
        rec += 1
        lines.append(frame("turn/completed", {
            "viewCursor": cursor(), "sessionId": SID, "turnId": turn,
            "terminal": "completed", "durationMs": 1200,
            "sourceRange": rng(SID, rec),
        }))

    header = (
        "# synthetic-stress-300.jsonl — GENERATED by fixtures/msp/make-stress-300.py, not a wire capture.\n"
        "#\n"
        "# ~300 turns in the synthetic-todo-goal envelope for the transcript scroll\n"
        "# benchmark (Task C item 3): every 10th turn carries three consecutive bash\n"
        "# toolCalls for the tool-group fold. Regenerate with:\n"
        "#\n"
        "#   python3 fixtures/msp/make-stress-300.py --turns 300\n"
        "#\n"
        "# The `synthetic-` prefix is load-bearing: nothing here was ever on a wire, and\n"
        "# it must never be read as evidence of what Muse does.\n"
    )
    with open(args.out, "w") as fh:
        fh.write(header)
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {args.turns} turns, {len(lines)} frames")


if __name__ == "__main__":
    sys.exit(main())
