//! The Muse Session Protocol (MSP) v1 wire schema, typed.
//!
//! Generated by hand from `fixtures/msp/msp-ts/msp.d.ts` (muse 1.2.1) and validated against the
//! live wire captures in `fixtures/msp/*.jsonl`. Every `export interface` and `export type` of the
//! published declarations has a counterpart here under the same name.
//!
//! # Where a type lives
//!
//! One file per wire surface, and every one of them is re-exported here, so
//! `muse_client::schema::Anything` is the path whatever the file
//! (finding `client-adapter-16`):
//!
//! | file | surface |
//! |---|---|
//! | `account.rs` | `account/*`: the credential lanes and the two login flows |
//! | `approval.rs` | `approval/*` (SS5) |
//! | `user_input.rs` | `userInput/*` (SS4.9) |
//! | `session.rs` | `session/*`, including every `session/*` notification |
//! | `turn.rs` | `turn/*` (SS3.2-3.6) and the token, todo and trace records |
//! | `view.rs` | `view/*` (SS4.7) and the items it pages |
//! | `model.rs` | `model/*` (SS3.10) and reasoning effort |
//! | `common.rs` | the envelope, errors, capabilities, platform, and the index |
//!
//! The envelope, the two enum macros and the `double_option` helper stay here,
//! because every file above uses them.
//!
//! # Conventions
//!
//! * Every struct is `#[serde(rename_all = "camelCase")]`; Rust fields are snake_case and the
//!   camelCase wire names are produced by serde.
//! * **Open** string unions (the ones msp.d.ts spells `… | (string & {})`) are unit enums with a
//!   final `Unknown` variant, so a value a newer server invents deserializes instead of failing.
//!   `as_wire()` returns the wire string, or `None` for `Unknown` — *serializing* `Unknown` cannot
//!   recover the original string and is a bug in the caller.
//! * **Closed** unions ([`AccountLoginType`], [`ApprovalMode`], [`HistoryPreference`], [`IfBusy`],
//!   [`ReasoningEffort`], [`TurnInputPartType`], [`UserInputSelectionMode`], [`ViewPageDirection`],
//!   [`PlatformFamily`], [`PlatformOs`], [`CommandAckStatus`], [`JsonRpcVersion`],
//!   [`ItemReadOutputEncoding`]) have no `Unknown`: an unrecognized
//!   value there is a real error and is reported as one.
//! * Optional members are `Option<T>` that skip serialization when `None`. **Required-nullable**
//!   members (present on the wire, `null` when empty) are `Option<T>` that serialize as `null`.
//!
//! # What the binary emits that the published index omits
//!
//! [`MSP_METHODS`] and [`MSP_NOTIFICATIONS`] are the SS1.9 index verbatim, and
//! [`MSP_SERVER_REQUESTS`] is the schema's own `requests` index verbatim (new in the muse 1.2.1
//! bundle — under 1.1.1 the two server→client requests were unindexed). The binary additionally
//! emits one thing no index lists, and a client must handle it:
//!
//! * the **`session/started` notification**, params `{"session": Session}` — modelled as
//!   [`SessionStartedParams`]. It arrives right after a `session/start` result.
//!
//! The **`userInput/request` and `approval/request` server→client *requests*** (not
//! notifications: they carry an `id` in the server's own id space) have params exactly
//! [`UserInputRequestParams`] and [`ApprovalRequestParams`], the same objects the
//! `userInput/requested` / `approval/requested` notifications carry — and since 1.2.1 those same
//! full payloads (not the documented `{kind, …}` pointers) are what `session/read`,
//! `session/resume` and `session/fork` serve in `pendingRequests`: see [`PendingRequestEntry`].
//!
//! # Where the wire contradicts msp.d.ts
//!
//! Five members msp.d.ts declares optional are, in the captures, always present and sometimes
//! explicitly `null` — they are modelled here as required-nullable so a re-serialized frame is
//! equal to what the server sent: [`Item::turn_id`], [`SessionTokenUsageParams::model_id`],
//! [`SessionBranchChangedParams::branch`], [`SessionModelChangedParams::provider_id`] and
//! [`SessionGoalChangedParams::goal`].

use serde::Deserialize;
use serde_json::{Map, Value};

/// Deserializer for an optional-**and**-nullable member, so that "key absent" and
/// "key present, `null`" stay distinguishable through a round trip.
fn double_option<'de, T, D>(de: D) -> Result<Option<Option<T>>, D::Error>
where
    T: Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    Option::<T>::deserialize(de).map(Some)
}

/// Declares an **open** string enum: unknown server values fold to `Unknown`, deliberately, because
/// the schema declares the domain open and a new value is additive evolution, not an error.
macro_rules! open_enum {
    (
        $(#[$outer:meta])*
        $name:ident { $( $variant:ident = $wire:literal ),* $(,)? }
    ) => {
        $(#[$outer])*
        ///
        /// **Open enum.** A value this build does not know deserializes to `Unknown(String)`
        /// rather than failing — that is deliberate: the schema declares this domain open. The
        /// original wire string is kept (finding `client-adapter-15`), so an `Unknown` value
        /// round-trips through serialization byte-exact instead of coming back as the literal
        /// `"Unknown"`. Use [`Self::as_wire`] for a *known* variant's wire string.
        #[derive(Clone, Debug, PartialEq, Eq, Hash)]
        pub enum $name {
            $(
                #[doc = concat!("The `", $wire, "` value.")]
                $variant,
            )*
            /// A value outside this build's vocabulary, with the original string it came in
            /// as — rendered generically, never as an error.
            Unknown(String),
        }

        impl $name {
            /// The wire string for this variant, or `None` for [`Self::Unknown`] — read its
            /// carried string directly for that case.
            #[must_use]
            pub fn as_wire(&self) -> Option<&'static str> {
                match self {
                    $( Self::$variant => Some($wire), )*
                    Self::Unknown(_) => None,
                }
            }
        }

        impl Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                match self {
                    $( Self::$variant => serializer.serialize_str($wire), )*
                    Self::Unknown(raw) => serializer.serialize_str(raw),
                }
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                let raw = String::deserialize(deserializer)?;
                Ok(match raw.as_str() {
                    $( $wire => Self::$variant, )*
                    _ => Self::Unknown(raw),
                })
            }
        }
    };
}

/// Declares a **closed** string enum: an unrecognized value is a real error and fails to decode.
macro_rules! closed_enum {
    (
        $(#[$outer:meta])*
        $name:ident { $( $variant:ident = $wire:literal ),* $(,)? }
    ) => {
        $(#[$outer])*
        ///
        /// **Closed enum.** An unrecognized value is a protocol error and fails to deserialize.
        #[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(rename_all = "camelCase")]
        pub enum $name {
            $(
                #[doc = concat!("The `", $wire, "` value.")]
                #[serde(rename = $wire)]
                $variant,
            )*
        }

        impl $name {
            /// The wire string for this variant.
            #[must_use]
            pub fn as_wire(&self) -> &'static str {
                match self {
                    $( Self::$variant => $wire, )*
                }
            }
        }
    };
}

mod account;
mod approval;
mod common;
mod model;
mod session;
mod turn;
mod user_input;
mod view;

pub use account::*;
pub use approval::*;
pub use common::*;
pub use model::*;
pub use session::*;
pub use turn::*;
pub use user_input::*;
pub use view::*;
